FROM ruby:2.5.1 
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /app
WORKDIR /app 
ENV BUNDLER_VERSION=2.1.4
RUN gem update --system && \
    gem install bundler:2.1.4 && \
    gem install bunny && \
    gem install json && \
    gem install mysql2 
 
ADD . /app
CMD ["ruby" , "calculate_score.rb"]

